Input_File_Name=Cu3O.pov
Output_to_File=True
Output_File_Type=N
Output_Alpha=on
; if you adjust Height, and width, you must preserve the ratio
; Width / Height = 1.887191
Width=260.6677912837157
Height=138.12475331917474
Antialias=True
Antialias_Threshold=0.1
Display=False
Display_Gamma=sRGB
Pause_When_Done=True
Verbose=False
